### PR TITLE
feature: Update symfony/yaml dependency from "~2.1" to "^3.2".

### PR DESCRIPTION
**Pull request by golovetska**

### CODE REVIEW

**Comment by emahuni** [comment]
hi. could you take over for maintenance of this repo?

**Comment by fojuth** [comment]
Hey!

I'm not sure if I understand you correctly - do you want me to continue
maintaining the project? If so, the answer is no :( I don't have the time
to develop this package, sorry.

But I'm looking for a maintainer! So if you want to help with the project -
it would be great!

Z poważaniem,
Kamil Fojuth

2017-11-24 11:36 GMT+01:00 Emmanuel Mahuni <notifications@github.com>:

**Comment by golovetska** [comment]
Hey! I could try to take over of this repository :-)

**Comment by fojuth** [comment]
I'll be more than happy to have you on the project and pass the steering
wheel to you :)

Thank you so much!

Z poważaniem,
Kamil Fojuth

2017-11-30 17:51 GMT+01:00 golovetska <notifications@github.com>:

**Comment by golovetska** [comment]
Thanks!

**Pull request closed without merging**
